### ISSUE TITLE
browser not sending type3 message

### ISSUE THREAD

**Issue by jamesbillinger** [kkleokrish/passport-ntlm#2]
I've gotten this configured such that it is receiving a challenge from the domain controller and sending a type2 to the client.  However, I can't seem to get the client (IE or Firefox) to respond with a type3.

```
var passport2 = require('passport');
var NTLMStrategy = require('passport-ntlm').Strategy;
passport2.use(new NTLMStrategy({domain:'HAYSMED'},
  (username, done) => {
    var user={ username: username };
    return done(null, user);
  }
));
app.get('/ntlm', passport2.authenticate('ntlm', { session: false }),routes.views.auth.loginUser);
```

Any help, suggestions, thoughts would be appreciated.  BTW, this is a copy of the type2 response header:

```
Connection: keep-alive
Date: Fri, 29 Apr 2016 13:54:21 GMT
Transfer-Encoding: chunked
WWW-Authenticate: NTLM KwLw3wAAAAACAAAADgAOADAAAAABAoEAPHjWj8gcQH0AAAAAAAAAADAAMAA+AAAASABBAFkAUwBNAEUARAACAA4ASABBAFkAUwBNAEUARAAEABYAaABhAHkAcwBtAGUAZAAuAGMAbwBtAAAAAAA=
X-Frame-Options: sameorigin
X-Powered-By: Express
```

Thanks!

**Comment by daneshka** [comment]
Same problem here!

**Comment by kkleokrish** [comment]
This could happen due to multiple reasons.  
1) Client policy - http://stackoverflow.com/questions/16360718/ntlm-authentication-fails-after-type-2-response
2) If the Type 2 was perceived invalid by the browser for some reason. If you have wireshark or similar tool, you should be able to see if there are any errors in the message format.

**Comment by daneshka** [comment]
My problem solved.
It was because of nginx
http://stackoverflow.com/questions/21284935/nginx-reverse-proxy-with-windows-authentication-that-uses-ntlm

**Comment by kkleokrish** [comment]
James,

Was your issue fixed too? Could this issue be closed?

**Comment by jamesbillinger** [comment]
I believe (I'm hoping) that this fixed my issue as well.  We moved our auth to JWT with a dedicated API so that I could remove the need for nginx in front, and so far i haven't seen any crossed sessions.  We don't have much of our user base moved over yet, but I feel comfortable closing the issue and I will re-open should problems arise.

Thanks everyone for your help on this!
